FROM centos:latest
RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum update -y
RUN yum install java-11-openjdk-devel -y
RUN mkdir /opt/maven
ADD https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz .
RUN tar -xvzf apache-maven-3.8.5-bin.tar.gz
RUN mv apache-maven-3.8.5/* /opt/maven
ENV PATH=$PATH:/opt/maven/bin
RUN mvn --version
RUN yum install git -y
RUN git clone https://github.com/Prhg8/javawebapp.git /opt/maven/maven
WORKDIR /opt/maven/maven/
RUN mvn clean package